// SPDX-License-Identifier: GPL-2.0-only
//!
//! Intel Management Engine Interface (MEI/HECI) kernel-side client driver.
//!
//! # What this does
//!
//! Registers a `mei_cl_driver` that binds to the MKHI (ME Kernel Host
//! Interface) MEI bus client, sends a `GET_FW_VERSION` MKHI command, and
//! stores the resulting firmware version string in a module-level cell so
//! it can be included in the `/proc/sysentinel_metrics` read output.
//!
//! # Build requirement
//!
//! This file is compiled only when `--cfg mei_available` is passed to rustc,
//! which happens when you run:
//!
//! ```sh
//! make MEI=y KDIR=/path/to/kernel/source
//! ```
//!
//! Your kernel must have `CONFIG_INTEL_MEI=y` or `CONFIG_INTEL_MEI=m`.
//! If the MEI subsystem is a module, load it before loading sysentinel:
//! `modprobe mei_me && insmod sysentinel_metrics.ko`
//!
//! # Why we use extern "C" here
//!
//! The Linux kernel's MEI subsystem does not yet have upstream Rust bindings
//! in `rust/kernel/`. Until those land, we reach the C MEI bus API directly
//! through `extern "C"` declarations. Every declaration here mirrors the
//! corresponding symbol in `include/linux/mei_cl_bus.h`; verify the
//! signatures against your kernel version before building.
//!
//! # AMD PSP note
//!
//! AMD PSP firmware-version queries require ring-0 access to an MSR-based
//! mailbox (`MP0_SMN_C2P_MSG_0` / `MP0_SMN_C2P_MSG_1` at SMN addresses
//! `0x3B10528` / `0x3B10924` on Ryzen), and on recent AMD platforms this
//! mailbox is firewalled from the x86 side entirely. Reliable PSP status
//! from user-space is exposed via `/dev/tpm0` or sysfs; that path is
//! handled in `daemon/src/mei.rs` without requiring any ring-0 access.
//!
//! # License
//!
//! GPL-2.0-only — required for use with in-kernel symbols.

#![allow(dead_code)]
#![cfg(mei_available)]

use kernel::error::from_err_ptr;
use kernel::prelude::*;
use kernel::sync::global_lock;

// ── MKHI MEI client GUID ──────────────────────────────────────────────────────

/// UUID for the MKHI MEI bus client, in little-endian wire format.
///
/// Standard value: `{8e6a6715-9abc-4043-88ef-9e39c6f63e0f}`
///
/// This is the ME client that handles firmware-management commands, including
/// the `GET_FW_VERSION` request (Group 0xFF, Command 0x02).
const MKHI_MEI_GUID: [u8; 16] = [
    // time_low (4 bytes, LE): 0x8e6a6715
    0x15, 0x67, 0x6a, 0x8e,
    // time_mid (2 bytes, LE): 0x9abc
    0xbc, 0x9a,
    // time_hi_and_version (2 bytes, LE): 0x4043
    0x43, 0x40,
    // clock_seq_and_reserved + clock_seq_low (2 bytes, big-endian in RFC 4122)
    0x88, 0xef,
    // node (6 bytes)
    0x9e, 0x39, 0xc6, 0xf6, 0x3e, 0x0f,
];

// ── FFI: mei_cl_bus.h types and functions ─────────────────────────────────────

/// Opaque placeholder for `struct mei_cl_device` (from mei_cl_bus.h).
///
/// We never inspect or construct this struct — we only hold a pointer to it
/// as passed by the MEI bus in the `probe` callback.
#[repr(C)]
pub struct MeiClDevice {
    _opaque: core::marker::PhantomData<*mut u8>,
}

/// Opaque placeholder for `struct mei_cl_driver`.
///
/// In a real kernel-module-with-full-Rust-MEI-bindings world, this would be
/// a proper Rust struct with a vtable. For now we maintain it in a C static
/// and register/unregister it via the FFI calls below.
#[repr(C)]
pub struct MeiClDriver {
    _opaque: core::marker::PhantomData<*mut u8>,
}

/// Function-pointer table filled in by our C shim (`mei_shim.c`).
///
/// Because Rust kernel modules cannot yet express the C `struct mei_cl_driver`
/// layout (it contains function pointers and embedded structs not represented
/// in the kernel's Rust bindings), we provide a small C shim file that:
///   1. Defines the static `mei_cl_driver` struct,
///   2. Registers it with `mei_cl_driver_register()`,
///   3. Calls back into `sysentinel_mei_probe` / `sysentinel_mei_remove`
///      (Rust functions exported via `no_mangle`).
///
/// See `kernel_module/src/mei_shim.c` (generated by the Makefile) for the
/// boilerplate.
extern "C" {
    /// Register the sysentinel MEI client driver. Returns 0 on success,
    /// negative errno on failure. Wraps `mei_cl_driver_register()`.
    fn sysentinel_mei_register() -> core::ffi::c_int;

    /// Unregister the sysentinel MEI client driver. Wraps
    /// `mei_cl_driver_unregister()`.
    fn sysentinel_mei_unregister();

    /// Send a buffer to the connected MEI device.
    /// Wraps `mei_cldev_send()` (kernel ≥ 4.11) / `mei_cl_send()` (older).
    fn sysentinel_mei_send(
        cldev: *mut MeiClDevice,
        buf: *const u8,
        len: usize,
    ) -> isize;

    /// Receive a buffer from the connected MEI device.
    /// Wraps `mei_cldev_recv()` / `mei_cl_recv()`.
    fn sysentinel_mei_recv(
        cldev: *mut MeiClDevice,
        buf: *mut u8,
        len: usize,
    ) -> isize;
}

// ── Shared firmware-version state ─────────────────────────────────────────────

/// Global storage for the Intel ME firmware version, populated by the MEI
/// probe callback and read by the metrics device.
///
/// `None` before the MEI client binds, or on systems without Intel ME.
global_lock! {
    // SAFETY: `ME_VERSION.init()` is called exactly once, from the module
    // initializer (`ensure_initialized`), before the value is ever accessed.
    unsafe(uninit) static ME_VERSION: Mutex<Option<MeFwVersion>> = None;
}

/// Initialize the ME firmware-version lock. Must be called exactly once,
/// before the first read or write (i.e. from the module initializer).
pub fn ensure_initialized() {
    // SAFETY: The module initializer runs once, before any access.
    unsafe { ME_VERSION.init() };
}

/// Parsed Intel ME firmware version.
#[derive(Debug, Clone, Copy)]
pub struct MeFwVersion {
    pub major: u16,
    pub minor: u16,
    pub build: u16,
    pub hotfix: u16,
}

/// Read the cached ME firmware version (non-blocking; returns the last known
/// value or `None` if the MEI client has not bound yet).
pub fn get_me_fw_version() -> Option<MeFwVersion> {
    *ME_VERSION.lock()
}

// ── MKHI message format ───────────────────────────────────────────────────────

/// MKHI message header — 4 bytes, little-endian packed.
///
/// This follows the layout spoken by Intel's own userspace tools
/// (`mei-tools/src/mkhi.h`, `intelmetool`) and the ME firmware reference:
/// ```text
/// Bits [7:0]   = Group ID        (0 = GEN/general group)
/// Bits [15:8]  = Command ID
/// Bit  [16]    = Is Response     (ME stamps it in replies; zero in host requests)
/// Bits [23:17] = Reserved
/// Bits [31:24] = Result / status (0 = success; non-zero on MKHI errors)
/// ```
///
/// > The previous revision of this file used a different bitfield layout
/// > (7-bit command at [11:8], response bit at [12], 16-bit length at [31:16])
/// > on group 0xFF. That does not match the GEN `GET_FW_VERSION` wire format,
/// > which is why real ME replies were misparsed as "IS_RESPONSE not set".
/// > Keep this header in sync with `mei-tools`; it is the field-proven shape.
#[repr(C, packed)]
#[derive(Debug, Clone, Copy)]
struct MkhiHeader {
    raw: u32,
}

impl MkhiHeader {
    /// Build a host request header: group + command, no response bit, no result.
    const fn request(group_id: u8, command: u8) -> Self {
        Self {
            raw: (group_id as u32) | ((command as u32) << 8),
        }
    }

    fn group(self) -> u8 {
        (self.raw & 0xff) as u8
    }

    fn command(self) -> u8 {
        ((self.raw >> 8) & 0xff) as u8
    }

    fn is_response(self) -> bool {
        ((self.raw >> 16) & 1) == 1
    }

    fn result(self) -> u8 {
        ((self.raw >> 24) & 0xff) as u8
    }
}

/// MKHI group and command for the firmware-version query.
///
/// `GET_FW_VERSION` is documented in the MKHI reference under the GEN group
/// (`0x00`), but on the silicon this module targets (Intel ME CSE
/// `16.1.2255.30`) the firmware answers the query **only** from group `0xFF`:
/// a request on `.00` gets a header-only status rejection, while `0xFF` yields
/// the full version response (verified empirically — see git history for the
/// legacy build). The command id stays `0x02`.
const MKHI_GROUP_ID: u8 = 0xFF;
const MKHI_CMD_GET_FW_VERSION: u8 = 0x02;

/// A response is acceptable only when the ME stamped IS_RESPONSE, echoed the
/// request's group/command, and reported a zero result byte.
fn response_is_valid(header: &MkhiHeader) -> bool {
    header.is_response()
        && header.group() == MKHI_GROUP_ID
        && header.command() == MKHI_CMD_GET_FW_VERSION
        && header.result() == 0
}

/// Request message for GET_FW_VERSION (header only; no payload).
#[repr(C, packed)]
struct GetFwVersionRequest {
    header: MkhiHeader,
}

/// Response message for GET_FW_VERSION.
///
/// Two version triples are returned: code (the running image) and recovery
/// (the recovery partition). We use the code version. All fields are LE u16.
#[repr(C, packed)]
#[allow(dead_code)]
struct GetFwVersionResponse {
    header: MkhiHeader,
    code_minor:  u16,
    code_major:  u16,
    code_build:  u16,
    code_hotfix: u16,
    recovery_minor:  u16,
    recovery_major:  u16,
    recovery_build:  u16,
    recovery_hotfix: u16,
}

/// How many times we re-issue the GET_FW_VERSION exchange before giving up.
const MAX_ATTEMPTS: u32 = 5;
/// Pause between attempts (ms). The ME can take a while to settle at boot, and
/// `mei_cldev_recv` bounds each read (~1 s) so a hung ME cannot wedge us.
const RETRY_DELAY_MS: u64 = 50;

// ── MEI probe / remove callbacks (called from C shim) ────────────────────────

/// Called by the MEI bus when a matching client device is found.
///
/// This function is exported with `#[no_mangle]` so the C shim can set it as
/// the `.probe` callback in the `struct mei_cl_driver`.
///
/// # Safety
///
/// `cldev` is a valid `struct mei_cl_device *` provided by the MEI bus
/// framework. Its lifetime is managed by the bus — it remains valid until
/// `sysentinel_mei_remove` returns.
#[no_mangle]
pub unsafe extern "C" fn sysentinel_mei_probe(cldev: *mut MeiClDevice) -> core::ffi::c_int {
    pr_info!("sysentinel: MEI MKHI client probed; querying ME firmware version\n");

    match unsafe { query_me_fw_version(cldev) } {
        Ok(ver) => {
            pr_info!(
                "sysentinel: Intel ME firmware version {}.{}.{}.{}\n",
                ver.major, ver.minor, ver.build, ver.hotfix
            );
            *ME_VERSION.lock() = Some(ver);
            0 // success
        }
        Err(e) => {
            pr_err!(
                "sysentinel: failed to query Intel ME firmware version: {:?}\n",
                e
            );
            // Return 0 anyway — we don't want to prevent the module from
            // loading just because the version query failed (e.g. ME in
            // manufacturing mode, or MKHI client not available on this SKU).
            0
        }
    }
}

/// Called by the MEI bus when the client device is removed or the module
/// is unloaded.
///
/// # Safety
///
/// `cldev` is the same pointer originally passed to `sysentinel_mei_probe`.
#[no_mangle]
pub unsafe extern "C" fn sysentinel_mei_remove(_cldev: *mut MeiClDevice) {
    pr_info!("sysentinel: MEI MKHI client removed\n");
    *ME_VERSION.lock() = None;
}

// ── Version query implementation ──────────────────────────────────────────────

/// Outcome of a single MKHI exchange attempt.
#[derive(Debug, Clone, Copy)]
enum QueryErr {
    /// Transient — ME still settling, stale or short reply; safe to retry.
    Transient,
    /// The ME answered header-only with a definitive MKHI status code.
    Status(u8),
}

/// Issue a single GET_FW_VERSION exchange: build the request, send it, read the
/// reply into a fixed 64-byte buffer, and validate the MKHI header ourselves
/// (IS_RESPONSE bit, echoed group/command, zero result, sane payload).
///
/// The ME can deliver replies split across reads (header first, version data
/// next) or answer header-only with a status. We therefore keep reading until
/// we hold at least the 4-byte header, then branch on its content:
/// `QueryErr::Transient` for anything that deserves another attempt, and
/// `QueryErr::Status(n)` when the firmware definitively rejected the command.
///
/// Reads of the *code* version start at byte 4 of the reply; the recovery
/// triple follows at byte 12 but is not needed here.
///
/// # Safety
///
/// `cldev` must be a valid, connected `struct mei_cl_device *` as provided by
/// the MEI bus in the `probe` callback.
unsafe fn try_query_once(cldev: *mut MeiClDevice) -> Result<MeFwVersion, QueryErr> {
    // Build the request (header only, no payload).
    let req = GetFwVersionRequest {
        header: MkhiHeader::request(MKHI_GROUP_ID, MKHI_CMD_GET_FW_VERSION),
    };

    // SAFETY: `cldev` is valid; `req` is a POD packed struct whose bytes are
    // exactly the on-wire MKHI message (this is a raw byte exchange, so a
    // packed repr pins the layout).
    let sent = unsafe {
        sysentinel_mei_send(
            cldev,
            core::ptr::addr_of!(req) as *const u8,
            core::mem::size_of::<GetFwVersionRequest>(),
        )
    };

    if sent != core::mem::size_of::<GetFwVersionRequest>() as isize {
        pr_warn!("sysentinel: MKHI send returned {sent}; will retry\n");
        return Err(QueryErr::Transient);
    }

    // Read the reply into a fixed buffer. We deliberately do NOT size the read
    // to GetFwVersionResponse so that a bogus/oversized reply cannot overrun a
    // stack struct and we can distinguish short reads from valid headers. Most
    // MEs deliver the whole message in one read, so the loop usually exits
    // after the first iteration.
    let mut buf = [0u8; 64];
    let mut total = 0usize;
    for _ in 0..3 {
        // SAFETY: `buf[total..]` is a writable kernel buffer; length is bounded
        // by `buf.len() - total` (total never exceeds buf.len()).
        let r = unsafe {
            sysentinel_mei_recv(cldev, buf[total..].as_mut_ptr(), buf.len() - total)
        };
        if r < 0 {
            pr_warn!("sysentinel: MKHI recv error ({r}); will retry\n");
            return Err(QueryErr::Transient);
        }
        total += r as usize;
        if total >= core::mem::size_of::<MkhiHeader>() {
            break;
        }
    }

    if total < core::mem::size_of::<MkhiHeader>() {
        pr_warn!(
            "sysentinel: MKHI no usable reply header ({total} bytes); will retry\n"
        );
        return Err(QueryErr::Transient);
    }

    let header = MkhiHeader {
        raw: u32::from_le_bytes(buf[0..4].try_into().unwrap()),
    };

    if !response_is_valid(&header) {
        pr_warn!(
            "sysentinel: MKHI reply invalid (group={:#x} cmd={:#x} is_resp={}\
             result={:#x}, {} bytes); will retry\n",
            header.group(),
            header.command(),
            header.is_response() as u8,
            header.result(),
            total,
        );
        return Err(QueryErr::Transient);
    }

    if header.result() != 0 {
        // Header-only error reply: the firmware rejected the command outright.
        // Surface the status so the retry loop can stop hammering it.
        return Err(QueryErr::Status(header.result()));
    }

    let min_good =
        core::mem::size_of::<MkhiHeader>() + 4 * core::mem::size_of::<u16>();
    if total < min_good {
        // The ME often answers the first query with nothing or a stub during
        // early boot; that is precisely the transient case to retry.
        pr_warn!(
            "sysentinel: MKHI response too short ({total} bytes, need {min_good});\
             ME may still be settling — will retry\n"
        );
        return Err(QueryErr::Transient);
    }

    let code_minor  = u16::from_le_bytes(buf[4..6].try_into().unwrap());
    let code_major  = u16::from_le_bytes(buf[6..8].try_into().unwrap());
    let code_build  = u16::from_le_bytes(buf[8..10].try_into().unwrap());
    let code_hotfix = u16::from_le_bytes(buf[10..12].try_into().unwrap());

    Ok(MeFwVersion {
        major:  code_major,
        minor:  code_minor,
        build:  code_build,
        hotfix: code_hotfix,
    })
}

/// Exchange a GET_FW_VERSION MKHI request/response with the ME, retrying on
/// transient failures (ME busy at boot, bogus or stale replies, short reads)
/// and stopping early once the firmware provably rejected the command.
///
/// Retries are bounded by [`MAX_ATTEMPTS`], with a short pause between attempts
/// so the ME firmware can finish coming up. `mei_cldev_recv` itself bounds each
/// read (~1 s) so a hung ME cannot wedge the probe worker indefinitely.
///
/// # Safety
///
/// `cldev` must be a valid, connected `struct mei_cl_device *` as provided by
/// the MEI bus in the `probe` callback.
unsafe fn query_me_fw_version(cldev: *mut MeiClDevice) -> Result<MeFwVersion> {
    let mut stable_status: Option<u8> = None;
    for attempt in 0..MAX_ATTEMPTS {
        // SAFETY: `cldev` stays valid for the whole probe; true on each pass.
        match unsafe { try_query_once(cldev) } {
            Ok(v) => return Ok(v),
            Err(QueryErr::Transient) => {
                // Pause before re-issuing. Probe runs in process context
                // (driver-core worker kthread), so sleeping is permitted; no
                // spinlocks are held across this. `fsleep` picks the best
                // sleep primitive for the duration.
                if attempt + 1 < MAX_ATTEMPTS {
                    kernel::time::delay::fsleep(kernel::time::Delta::from_millis(
                        RETRY_DELAY_MS as i64,
                    ));
                }
            }
            Err(QueryErr::Status(code)) => {
                // Firmware answered with a definitive status. Retry once in
                // case it was momentarily busy, then stop and report.
                if stable_status == Some(code) {
                    pr_err!(
                        "sysentinel: MKHI GET_FW_VERSION persistently rejected with\
                         status {code:#x}; ignoring ME firmware version\n"
                    );
                    return Err(EIO);
                }
                stable_status = Some(code);
                if attempt + 1 < MAX_ATTEMPTS {
                    kernel::time::delay::fsleep(kernel::time::Delta::from_millis(
                        RETRY_DELAY_MS as i64,
                    ));
                }
            }
        }
    }
    pr_err!(
        "sysentinel: MKHI GET_FW_VERSION failed after {MAX_ATTEMPTS} attempts;\
         ignoring ME firmware version\n"
    );
    Err(EIO)
}

// ── Module-level init / exit hooks ───────────────────────────────────────────

/// Register the MEI client driver. Called from the module's `init()`.
///
/// Returns `Ok(())` on success. A return of `Err(ENODEV)` means the MEI
/// subsystem is not present (no Intel ME on this platform); the module should
/// continue loading without MEI support.
pub fn register() -> Result<()> {
    // SAFETY: `sysentinel_mei_register` is provided by our C shim and calls
    // the kernel's `mei_cl_driver_register()` with a fully initialised struct.
    let ret = unsafe { sysentinel_mei_register() };
    if ret == 0 {
        pr_info!("sysentinel: MEI MKHI client driver registered\n");
        Ok(())
    } else if ret == -(ENODEV.to_errno() as i32) {
        pr_warn!("sysentinel: MEI subsystem not available (no Intel ME); continuing without it\n");
        Err(ENODEV)
    } else {
        pr_err!("sysentinel: mei_cl_driver_register failed: {}\n", ret);
        Err(from_err_ptr(ret as *mut core::ffi::c_void).unwrap_err())
    }
}

/// Unregister the MEI client driver. Called from the module's `drop()`.
pub fn unregister() {
    // SAFETY: symmetric with `register()`.
    unsafe { sysentinel_mei_unregister() };
    pr_info!("sysentinel: MEI MKHI client driver unregistered\n");
}
